### ISSUE TITLE
getting an error while installation

### ISSUE THREAD

**Issue by adityaprasad502** [ppizarror/PyMultiDictionary#10]
![image](https://user-images.githubusercontent.com/70315903/153747785-2345f71f-f106-4b3c-a04a-a0a4c7fe6f53.png)

I am getting this 'python setup.py egg_info did not run successfully. exit code: 1' error while trying to install  'PyMultiDictionary' package  🤔

**Comment by ppizarror** [comment]
I can confirm this. Are you using python 3.9 or newer? The problem relies on "goslate" package. You could see the same output if run:

```bash
py -3.9  -m pip install goslate
```

Will return the same issue. I'll patch it asap

**Comment by ppizarror** [comment]
Fixed in #11. I'm going to upload to PyPI. Let me know if any other issue happens :)

**Comment by adityaprasad502** [comment]
![image](https://user-images.githubusercontent.com/70315903/153877343-37a49288-f08d-4dc3-836d-b8aad249db11.png)

its installing fine now. 💖
