### ISSUE TITLE
Does not generate synonym

### ISSUE THREAD

**Issue by arifaisal123** [ppizarror/PyMultiDictionary#13]
**Environment information**
- OS: win
- python version: v3.11.1

**Describe the bug**
While requesting for the synonym of the word, the module returns an empty list. 
<img width="948" alt="bug" src="https://github.com/ppizarror/PyMultiDictionary/assets/92214243/bd618b8d-fa72-462e-a14d-90a6644feae2">

**To Reproduce**
While running the following code, instead of generating synonym, it returns an empty list. Other services, e.g.- meaning, antonym, translation are working fine.

`@app.route("/synonym", methods=["GET", "POST"])
def synonym():
    if request.method == "POST":
        word = request.form["synonym"]
        synonym = dictionary.synonym('en', word, dictionary=DICT_THESAURUS)
        return render_template("synonym.html", synonym=synonym)
    else:
        return render_template("synonym.html")`

**Expected behavior**
Getting synonym of the requested word.

**Comment by ppizarror** [comment]
Hello, the problem has been fixed in the new ``v1.2.3``! Please update with pip and let me know if it works 😄

**Comment by arifaisal123** [comment]
Thank you. It is working with the new version (v1.2.3).
