### ISSUE TITLE
HTTP Error 429: Too Many Requests / list index out of range

### ISSUE THREAD

**Issue by Nico-VC** [ppizarror/PyMultiDictionary#15]
**Environment information**

- SO: win
- python version: v3.11

**Describe the bug**
'Getting HTTP Error 429: Too Many Requests' exception when attempting to use MultiDictionary.translate().

I also get 'Error: list index out of range' instead of HTTP error at times. Can't reproduce one error consistently. 

Returning either 
```
UserWarning: range cannot be translated to ru-language as Google API is not available. Error: HTTP Error 429: Too Many Requests
  warn(f'{word} cannot be translated to {to}-language as Google API is not available. Error: {e}')
```
or 
```
UserWarning: range cannot be translated to ru-language as Google API is not available. Error: list index out of range
  warn(f'{word} cannot be translated to {to}-language as Google API is not available. Error: {e}')

```
when passing testing the word 'Range' from the doc example. 

**To Reproduce**
Encountering the issue with the following
```
from PyMultiDictionary import MultiDictionary

dictionary = MultiDictionary()
print(dictionary.translate('en', 'Range', to='ru'))

```
Instead of the specific translation for that language, a get a list of all the language translations.

Thanks! Trying to use this package for the first time.

**Comment by ppizarror** [comment]
Hi @Nico-VC. Sadly, for that, you need a Google Cloud API key. Otherwise, error 429 appears as this API limits number of requests, see https://github.com/yeahwhat-mc/goslate/issues/2.
There is no other alternative, you cannot bypass this limitation. One alternative is to use

```python
from PyMultiDictionary import MultiDictionary

dictionary = MultiDictionary()
print(dictionary.translate('en', 'Range'))
```

**Comment by Nico-VC** [comment]
I understand now! Thank you.
