### ISSUE TITLE
get_synonyms function not working

### ISSUE THREAD

**Issue by user-of-github-123** [ppizarror/PyMultiDictionary#17]
Python version: 3.6.4
I used this code:
from PyMultiDictionary import *
dictionary=MultiDictionary('angry')
dictionary.set_words_lang('en') # All words are english

print(dictionary.get_meanings(dictionary=DICT_EDUCALINGO)) # This print the meanings of all the words
print(dictionary.get_synonyms()) # Get synonyms list
print(dictionary.get_antonyms()) # Get antonyms

So far, only get_meanings() and get antonyms() worked. However, get_synonyms() returns an empty list for me

**Comment by ppizarror** [comment]
Hi. Have you updated the library version to 1.2.4? I have fixed a similar issue there

Pablo

**Comment by user-of-github-123** [comment]
Fixed, ty
